### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by djjudas21** [hsoft/dupeguru#420]
I'm attempting to write a spec file for this project so it can be built as an RPM for Red Hat, Fedora, CentOS, etc. I've got reasonably far (in that it builds a package which can be installed, but the binary fails when executed).

I see you're using virtualenv but unfortunately I know nothing about Python. It looks like a necessary module is missing but I don't really understand how virtualenv is supposed to work. Given that you've only provided OS X and Ubuntu packages, I guess that means you don't really understand how RPM is supposed to work, either!

Can you offer any advice? It could be that my built version of dupeGuru is using the system Python interpreter and moules, in which case I will have to find a way of providing the dependencies.

```
[jonathan@poseidon x86_64]$ /usr/local/bin/dupeguru
Traceback (most recent call last):
  File "/usr/local/bin/dupeguru", line 49, in <module>
    sys.exit(main())
  File "/usr/local/bin/dupeguru", line 35, in main
    from qt.app import DupeGuru
  File "/usr/local/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/local/share/dupeguru/core/app.py", line 14, in <module>
    from send2trash import send2trash
ImportError: No module named 'send2trash'
```

**Comment by hsoft** [comment]
Thanks for working on this! `send2trash` is a library on Pypi that dupeGuru depends on: https://pypi.python.org/pypi/Send2Trash/1.3.0

It's installable the usual way, `pip install send2trash`.

Now, about packaging it... First of all, yes, virtualenv is used for local development, but the for deb packaging, the final package doesn't use a virtualenv. If you're trying to package dupeGuru in a virtualenv in your RPM, you're probably doing it wrong.

Back to `send2trash`... Because it's not part of debian jessie or ubuntu xenial, I have to copy it into the final .deb. If you look at `package.py`, You'll see that I do just that. The error you're having is probably because you didn't copy send2trash in your final package.

**Comment by hsoft** [comment]
I have just noticed that you pushed your commit already and I see that you limit yourself to `make install`. That's fine, but as I write above, you're going to have to manually copy `send2trash` alongside the main `run.py` file because `make install` assumes that all dependencies are met on the system.
