### ISSUE TITLE
package.py fails due to moved file

### ISSUE THREAD

**Issue by Cebtenzzre** [hsoft/dupeguru#505]
I feel like I'm missing something obvious, because if what I believe to be true _is in fact true_, package.py has been failing for over a year.  But here goes anyway...

Commit 245ed0ddecd0fad4a8e8dab3be07d319c14b1514 seems to have made an incomplete change; package.py still references a file (/qt/run_template.py) that has been moved to /run.py in the referenced commit.  At least on my system, the attempt to delete the file [here](https://github.com/hsoft/dupeguru/blob/master/package.py#L38) fails.

Does "unmaintained" really mean "even the most basic of features fail altogether", is the master branch improperly used as an almost-never-working dev branch, am I missing something, or is some combination true?  Because the further I delve into the code, the less I feel like I understand.

**Comment by hsoft** [comment]
You are partially correct. It is true that the master branch has a broken `package.py` since the commit you're referencing (thanks for noticing). However, the last release, v4.0.3 predates this so `package.py` never had the opportunity to be ran since this breakage.

But yes, this will have to be fixed for a release to be packaged.

**Comment by hsoft** [comment]
If you want to work from something more stable, I suggest that you use the `4.0.3` tag. It might be a less frustrating experience.
